### ISSUE TITLE
Code folding lambda

### ISSUE THREAD

**Issue by miklossy** [i-BP/boem#18]
On the 'What's Next' slide of the [BOEM Project Presentation](https://www.youtube.com/watch?v=pS3QueML09s&t=534s) on the EclipseCon France 2018 you mentioned that you are missing the code folding functionality of Xtend lambda expressions. 

This feature is already supported by the Xtend IDE in version 2.13 and above: https://github.com/eclipse/xtext-xtend/issues/279

Would you please give it a try with the Xtend IDE 2.13 (or even 2.14) and conform that the functionality is working on your use case?

**Comment by jacobgeisel** [comment]
Thank you for mentioning that. We'll give it a try and give you feedback on that as soon as possible.

**Comment by jacobgeisel** [comment]
It works. Thanks again for the updates. I'll close the ticket and update a bit our presentation

**Comment by miklossy** [comment]
Nice. Thanks for the feedback!
