### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [i-BP/boem#19]
Hello BOEM team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the BOEM project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by jacobgeisel** [comment]
Hi @miklossy, Hi Xtext Team,
thank you for your proposal. We are happy to be mentioned on your communities page.

```
<tr>
	<td><a href="https://i-bp.github.io/boem/">BOEM. Builder Of EMF Models</a></td>
	<td>The aim of BOEM is to provide an API that eases the creation of EMF Models using XTend syntax and thus to create 'compiling' models. This helps to a) speed up the creation of tests, b) improve readability, c) improve maintainability when metamodels evolve and d) ease the creation of interconnected models.</td>
	<td>EPL</td>
	<td>Language, Framework</td>
	<td>Arthur Daussy, Jacob Geisel</td>
</tr>
```

Best regards,
Jacob

**Comment by miklossy** [comment]
Thank you @jacobgeisel !

**Comment by miklossy** [comment]
The `BOEM. Builder Of EMF Models` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
